name: Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]   # change en 'master' si besoin

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Show Python version
        run: python -V

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pyinstaller
          pip list

      - name: Build EXE (PyInstaller)
        run: |
          pyinstaller --noconfirm --name LEXIS --onefile --windowed app/__main__.py --collect-all PySide6

      - name: Upload artifact (LEXIS.exe)
        uses: actions/upload-artifact@v4
        with:
          name: LEXIS-windows-exe
          path: dist/LEXIS.exe

